import React from 'react';
import Head from "next/head";

function Header(props) {
    return (
        <Head>
            <title>duongdam - My profiles</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
    );
}

export default React.memo(Header);